### ISSUE TITLE
Reader stops working after removing Fingerprints from settings UI

### ISSUE THREAD

**Issue by eLtMosen** [piggz/sailfish-fpd-community#27]
Device: Pro¹ with sfos community port on 3.3.0.16

Daemon seems to crash or at least stop working right after removing a registered fingerprint using the settings UI.
To confirm the deletion it is not possible to use FP but the code has to be entered manually.

I first noticed this behaviour after deleting some of 8 registered FPs. Got suspicious that maybe the amount of registered FPs could be related. But that is not the case since this happens even when only having two FPs registered.

**Comment by piggz** [comment]
Logs such as journalctl | grep fpd would be useful, and maybe also from logcat

**Comment by shoukolate** [comment]
Unable to reproduce on jasmine_sprout community port 3.3.0.16

**Comment by eLtMosen** [comment]
Removal starts at 19:06:34

https://pastebin.com/2qrPjHiH

**Comment by rinigus** [comment]
"finger5" is rather large ID. I wonder if you should try to remove all FPs and then start using it again. Try to check out what is in the fingerprint database using our -test app. I wonder if there are some FPs that are not shown in Settings, but are enrolled/not deleted

**Comment by eLtMosen** [comment]
I had 5 FPs registered and ID 5 is the one i removed.
Still good advice, will remove all and try again. 
I had removed all but 2 to try if the amount had any influence as stated above. But did not remove all.

**Comment by rinigus** [comment]
@eLtMosen, did you unregistered all with our test app? or Jolla settings?

**Comment by eLtMosen** [comment]
All done in Settings.
Is there a recompiled version of the test app or step by step instructions how to?

**Comment by rinigus** [comment]
You can grab it here: https://build.merproject.org/package/show/nemo:devel:hw:sony:tama/sailfish-fpd-community-test

there is nothing there which is Sony-specific

**Comment by eLtMosen** [comment]
With the testing app all works as expected! No Problems at all.
Still if i now try to remove the new FP i registered in the test app using the jolla settings, the reader becomes unresponsive.
