### ISSUE TITLE
Aarch64 support

### ISSUE THREAD

**Issue by rinigus** [piggz/sailfish-fpd-community#34]
The SPEC files include 

```
%define device_rpm_architecture_string armv7hl
%define _target_cpu %{device_rpm_architecture_string}
```

which leads to RPMs that we cannot really install on aarch64 ports. Why do we need those?

**Comment by piggz** [comment]
I presume we coped the spec from another project .. can you remember where we copied it from?  Also, im sure @mlehtima already has some aarch64 patches for this ?

**Comment by rinigus** [comment]
no, I don't really remember where we got SPECs from.

**Comment by mlehtima** [comment]
https://github.com/piggz/sailfish-fpd-community/pull/35
