### ISSUE TITLE
Document how to enable fingerprint on device

### ISSUE THREAD

**Issue by rinigus** [piggz/sailfish-fpd-community#5]
* changes in config: added to /init.rc (based on https://github.com/erfanoabdi/android_device_halium_ubport/commit/eec61015dede9602f4fc6f704d53288a0e431593) . On Sony Tama, the following was sufficient

    # fingerprint
    mkdir /data/system/users/0 0700 system system
    mkdir /data/system/users/0/fpdata 0700 system system

* dropping  jolla-devicelock-plugin-encsfa and replacing it with sailfish-devicelock-fpd in patterns

**Comment by Thaodan** [comment]
Could you use systemd-tmpfiles for the directories?

**Comment by rinigus** [comment]
No, not really. Its persistent storage and location used by Android. As such, I think it's correct to let Android also to generate it.

**Comment by piggz** [comment]
I agree, its an android settings, so we should leave it in an .rc.  I have an idea that should cover all cases.

**Comment by piggz** [comment]
Documentation is in the readme
